---
swagger: "2.0"
info:
  version: "2018-03-02T12:02:37Z"
  title: "demo-index"
host: "kdbexr8frj.execute-api.eu-west-2.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /:
    get:
      consumes:
      - "application/json"
      produces:
      - "text/html"
      parameters:
      - name: "page"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Content-Type:
              type: "string"
